In [4]:
pip install langdetect

Collecting langdetect
  Downloading langdetect-1.0.9.tar.gz (981 kB)
     ---------------------------------------- 0.0/981.5 kB ? eta -:--:--
     -------------------- ----------------- 524.3/981.5 kB 8.5 MB/s eta 0:00:01
     ---------------------------------------- 981.5/981.5 kB 7.7 MB/s  0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: six in c:\users\user\.conda\envs\gemini_env\lib\site-packages (from langdetect) (1.17.0)
Building wheels for collected packages: langdetect
  Building wheel for langdetect (pyproject.toml): started
  Building wheel for langdetect (pyproject.toml): finished with status 'done'
  Created wheel for langdetect: filename=langdetect-1.0.9-py3-none-any.whl size=993363 sha256=f78fd8d12470edf8a0155c6f2ac4e40e631e22dc5d1c88545c4d489df9c91020
  Stored in directory: c:\users\user\appdata\local\pip\cache\wheels\95\03\7d\59ea870c70ce4e5a370638b5462a7711ab78fba2f655d05106
Successfully built langdetect
Installing collected packages: langdetect
Successfully installed langdetect-1.0.9
Note: you may need to restart the kernel to use updated packages.

In [5]:
pip install emoji

Collecting emoji
  Downloading emoji-2.15.0-py3-none-any.whl.metadata (5.7 kB)
Downloading emoji-2.15.0-py3-none-any.whl (608 kB)
   ---------------------------------------- 0.0/608.4 kB ? eta -:--:--
   ---------------------------------- ----- 524.3/608.4 kB 8.5 MB/s eta 0:00:01
   ---------------------------------------- 608.4/608.4 kB 5.5 MB/s  0:00:00
Installing collected packages: emoji
Successfully installed emoji-2.15.0
Note: you may need to restart the kernel to use updated packages.

In [6]:
import pandas as pd
import re
import emoji
from langdetect import detect

In [130]:
# 파일 경로

'''
comments_path = r"F:\porti\2025\스파르타자료들\python_study\venv\04_Team8\data_08\data\Reddit\ADCMains\comments_ADCMains.csv"
posts_path = r"F:\porti\2025\스파르타자료들\python_study\venv\04_Team8\data_08\data\Reddit\ADCMains\posts_ADCMains.csv"

save_path = r"F:\porti\2025\스파르타자료들\python_study\venv\04_Team8\data_08\data\Reddit\ADCMains\Data_ADCMains.csv"
'''

comments_path = r"F:\porti\2025\스파르타자료들\python_study\venv\04_Team8\data_08\data\Reddit\top_mains\comments_top_mains.csv"
posts_path = r"F:\porti\2025\스파르타자료들\python_study\venv\04_Team8\data_08\data\Reddit\top_mains\posts_top_mains.csv"

save_path = r"F:\porti\2025\스파르타자료들\python_study\venv\04_Team8\data_08\data\Reddit\top_mains\Data_top_mains.csv"

In [131]:
# 파일 읽기
comments = pd.read_csv(comments_path)
posts = pd.read_csv(posts_path)

In [132]:
# 날짜 변환
comments["comment_created_dt"] = pd.to_datetime(comments["comment_created_utc"], unit="s", errors="coerce")

posts["post_created_dt"] = pd.to_datetime(posts["created_utc"], unit="s", errors="coerce")

In [133]:
# deleted / removed 제거
comments = comments[~comments["comment_body"].isin(["[deleted]", "[removed]"])]

In [134]:
# bot 제거
comments = comments[~comments["comment_author"].str.contains("bot", case=False, na=False)]

In [135]:
# 중복 제거
comments = comments.drop_duplicates(subset=["comment_id"])

In [136]:
# 필요한 칼럼만 추출 후 이름 변경해주고 병합
posts = posts[["subreddit","id","title","post_created_dt","score","num_comments"
            ]].rename(columns={"id": "post_id","title": "post_title","score": "post_score","num_comments": "post_num_comments"})

comments = comments[["post_id","comment_id","comment_author","comment_score","comment_created_dt","comment_body"
            ]].rename(columns={"comment_body": "comment_body_raw"})

df = pd.merge(comments, posts, on="post_id", how="left")

In [137]:
df

,post_id,comment_id,comment_author,comment_score,comment_created_dt,comment_body_raw,subreddit,post_title,post_created_dt,post_score,post_num_comments
0,1pgj84n,nsrhoaf,mozes05,67,2025-12-07 14:13:04,Forgot one\n\nhttps://i.redd.it/3mdzzvpwb2t81.jpg,top_mains,Just saw that and had to share it,2025-12-07 14:09:41,3713,97
1,1pgj84n,nsrpome,Totoques22,64,2025-12-07 14:59:24,Unfortunately the scorpion 🦂 has not been good...,top_mains,Just saw that and had to share it,2025-12-07 14:09:41,3713,97
2,1pgj84n,nsrwqcw,MifiBox,22,2025-12-07 15:37:54,When the demonic catfish gets reduced to a fro...,top_mains,Just saw that and had to share it,2025-12-07 14:09:41,3713,97
3,1pgj84n,nssovx4,fozzy_fosbourne,17,2025-12-07 18:01:58,Jungle was all little weird freaks until the a...,top_mains,Just saw that and had to share it,2025-12-07 14:09:41,3713,97
4,1pgj84n,nsrs3po,SpectatorBeholder,7,2025-12-07 15:12:56,Actually he's a catfish,top_mains,Just saw that and had to share it,2025-12-07 14:09:41,3713,97
...,...,...,...,...,...,...,...,...,...,...,...
10039,1ogc8ju,nlfvy8a,The_God_of_Biscuits,0,2025-10-26 07:18:25,"If you have prio, you can crash whenever if jg...",top_mains,How do I stop accidentally giving freeze every...,2025-10-26 05:09:24,8,11
10040,1pc5che,nrv6swj,Desperate-Zebra-3855,15,2025-12-02 10:51:24,"As an example, Aatrox gets roughly 5 ad per le...",top_mains,"Hello fellow top mains, i have just finished w...",2025-12-02 10:44:27,8,6
10041,1pc5che,nrw4lvq,Active-Advisor5909,3,2025-12-02 14:45:32,Steraks will be slightly better. But a bonus 6...,top_mains,"Hello fellow top mains, i have just finished w...",2025-12-02 10:44:27,8,6
10042,1pc5che,nsg25jd,Mindless-Humor-9036,1,2025-12-05 16:21:43,I think you’re over thinking it tbh. I only go...,top_mains,"Hello fellow top mains, i have just finished w...",2025-12-02 10:44:27,8,6
10043,1r4ekpt,o5v2b4s,schobesa,1,2026-02-17 13:30:26,how the fuck did voli sign a poster?????????,top_mains,Volibear signed poster,2026-02-14 07:38:00,8,1

In [138]:
# 이모지 추출
def extract_emojis(text):
    return [c for c in text if c in emoji.EMOJI_DATA]

df["emoji_list"] = df["comment_body_raw"].apply(
    lambda x: extract_emojis(str(x))
)

df["emoji_count"] = df["emoji_list"].apply(len)

In [139]:
# 텍스트 정리
def clean_text(text):
    if pd.isna(text):
        return ""
    text = text.lower()
    text = re.sub(r"http\S+", "", text)  # URL 제거
    text = re.sub(r"\b\d{1,2}:\d{2}\b", "", text)  # timestamp 제거
    text = re.sub(r"[^가-힣a-zA-Z0-9\s]", "", text)  # 특수문자 제거
    text = re.sub(r"\s+", " ", text).strip()
    return text

df["comment_body_clean"] = df["comment_body_raw"].apply(clean_text)

In [140]:
df

,post_id,comment_id,comment_author,comment_score,comment_created_dt,comment_body_raw,subreddit,post_title,post_created_dt,post_score,post_num_comments,emoji_list,emoji_count,comment_body_clean
0,1pgj84n,nsrhoaf,mozes05,67,2025-12-07 14:13:04,Forgot one\n\nhttps://i.redd.it/3mdzzvpwb2t81.jpg,top_mains,Just saw that and had to share it,2025-12-07 14:09:41,3713,97,[],0,forgot one
1,1pgj84n,nsrpome,Totoques22,64,2025-12-07 14:59:24,Unfortunately the scorpion 🦂 has not been good...,top_mains,Just saw that and had to share it,2025-12-07 14:09:41,3713,97,"[🦂, 🐸, 🐏, 🔥, 🪓, 🧟]",6,unfortunately the scorpion has not been good i...
2,1pgj84n,nsrwqcw,MifiBox,22,2025-12-07 15:37:54,When the demonic catfish gets reduced to a fro...,top_mains,Just saw that and had to share it,2025-12-07 14:09:41,3713,97,"[🥀, 🥀]",2,when the demonic catfish gets reduced to a frog
3,1pgj84n,nssovx4,fozzy_fosbourne,17,2025-12-07 18:01:58,Jungle was all little weird freaks until the a...,top_mains,Just saw that and had to share it,2025-12-07 14:09:41,3713,97,[],0,jungle was all little weird freaks until the a...
4,1pgj84n,nsrs3po,SpectatorBeholder,7,2025-12-07 15:12:56,Actually he's a catfish,top_mains,Just saw that and had to share it,2025-12-07 14:09:41,3713,97,[],0,actually hes a catfish
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10039,1ogc8ju,nlfvy8a,The_God_of_Biscuits,0,2025-10-26 07:18:25,"If you have prio, you can crash whenever if jg...",top_mains,How do I stop accidentally giving freeze every...,2025-10-26 05:09:24,8,11,[],0,if you have prio you can crash whenever if jg ...
10040,1pc5che,nrv6swj,Desperate-Zebra-3855,15,2025-12-02 10:51:24,"As an example, Aatrox gets roughly 5 ad per le...",top_mains,"Hello fellow top mains, i have just finished w...",2025-12-02 10:44:27,8,6,[],0,as an example aatrox gets roughly 5 ad per lev...
10041,1pc5che,nrw4lvq,Active-Advisor5909,3,2025-12-02 14:45:32,Steraks will be slightly better. But a bonus 6...,top_mains,"Hello fellow top mains, i have just finished w...",2025-12-02 10:44:27,8,6,[],0,steraks will be slightly better but a bonus 6 ...
10042,1pc5che,nsg25jd,Mindless-Humor-9036,1,2025-12-05 16:21:43,I think you’re over thinking it tbh. I only go...,top_mains,"Hello fellow top mains, i have just finished w...",2025-12-02 10:44:27,8,6,[],0,i think youre over thinking it tbh i only go s...
10043,1r4ekpt,o5v2b4s,schobesa,1,2026-02-17 13:30:26,how the fuck did voli sign a poster?????????,top_mains,Volibear signed poster,2026-02-14 07:38:00,8,1,[],0,how the fuck did voli sign a poster

In [141]:
# 언어 감지 (조금 걸림!! 느림)
def detect_lang(text):
    try:
        return detect(text)
    except:
        return "unknown"

df["language"] = df["comment_body_clean"].apply(detect_lang)

In [142]:
# 컬럼 정렬
df = df[[
    "subreddit",
    "post_id",
    "post_title",
    "post_created_dt",
    "post_score",
    "post_num_comments",
    "comment_id",
    "comment_author",
    "comment_score",
    "comment_created_dt",
    "comment_body_raw",
    "comment_body_clean",
    "emoji_list",
    "emoji_count",
    "language"
]]

In [143]:
df

,subreddit,post_id,post_title,post_created_dt,post_score,post_num_comments,comment_id,comment_author,comment_score,comment_created_dt,comment_body_raw,comment_body_clean,emoji_list,emoji_count,language
0,top_mains,1pgj84n,Just saw that and had to share it,2025-12-07 14:09:41,3713,97,nsrhoaf,mozes05,67,2025-12-07 14:13:04,Forgot one\n\nhttps://i.redd.it/3mdzzvpwb2t81.jpg,forgot one,[],0,en
1,top_mains,1pgj84n,Just saw that and had to share it,2025-12-07 14:09:41,3713,97,nsrpome,Totoques22,64,2025-12-07 14:59:24,Unfortunately the scorpion 🦂 has not been good...,unfortunately the scorpion has not been good i...,"[🦂, 🐸, 🐏, 🔥, 🪓, 🧟]",6,en
2,top_mains,1pgj84n,Just saw that and had to share it,2025-12-07 14:09:41,3713,97,nsrwqcw,MifiBox,22,2025-12-07 15:37:54,When the demonic catfish gets reduced to a fro...,when the demonic catfish gets reduced to a frog,"[🥀, 🥀]",2,en
3,top_mains,1pgj84n,Just saw that and had to share it,2025-12-07 14:09:41,3713,97,nssovx4,fozzy_fosbourne,17,2025-12-07 18:01:58,Jungle was all little weird freaks until the a...,jungle was all little weird freaks until the a...,[],0,en
4,top_mains,1pgj84n,Just saw that and had to share it,2025-12-07 14:09:41,3713,97,nsrs3po,SpectatorBeholder,7,2025-12-07 15:12:56,Actually he's a catfish,actually hes a catfish,[],0,en
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10039,top_mains,1ogc8ju,How do I stop accidentally giving freeze every...,2025-10-26 05:09:24,8,11,nlfvy8a,The_God_of_Biscuits,0,2025-10-26 07:18:25,"If you have prio, you can crash whenever if jg...",if you have prio you can crash whenever if jg ...,[],0,en
10040,top_mains,1pc5che,"Hello fellow top mains, i have just finished w...",2025-12-02 10:44:27,8,6,nrv6swj,Desperate-Zebra-3855,15,2025-12-02 10:51:24,"As an example, Aatrox gets roughly 5 ad per le...",as an example aatrox gets roughly 5 ad per lev...,[],0,en
10041,top_mains,1pc5che,"Hello fellow top mains, i have just finished w...",2025-12-02 10:44:27,8,6,nrw4lvq,Active-Advisor5909,3,2025-12-02 14:45:32,Steraks will be slightly better. But a bonus 6...,steraks will be slightly better but a bonus 6 ...,[],0,en
10042,top_mains,1pc5che,"Hello fellow top mains, i have just finished w...",2025-12-02 10:44:27,8,6,nsg25jd,Mindless-Humor-9036,1,2025-12-05 16:21:43,I think you’re over thinking it tbh. I only go...,i think youre over thinking it tbh i only go s...,[],0,en
10043,top_mains,1r4ekpt,Volibear signed poster,2026-02-14 07:38:00,8,1,o5v2b4s,schobesa,1,2026-02-17 13:30:26,how the fuck did voli sign a poster?????????,how the fuck did voli sign a poster,[],0,en

In [ ]:
# 저장
df.to_csv(save_path, index=False, encoding="utf-8-sig")

print("저장 완료")

저장 완료

In [ ]:
'''
Data_ADBMains.csv
Data_Jungle_Mains.csv
Data_leagueoflegends.csv
Data_LeagueOfMemes.csv
Data_midlanemains.csv
Data_summonerschool.csv
Data_supportlol.csv
Data_top_mains.csv
'''

In [7]:
file_paths = [
    r"F:\porti\2025\스파르타자료들\python_study\venv\04_Team8\data_08\data\Reddit\ADCMains\Data_ADCMains.csv",
    r"F:\porti\2025\스파르타자료들\python_study\venv\04_Team8\data_08\data\Reddit\Jungle_Mains\Data_Jungle_Mains.csv",
    r"F:\porti\2025\스파르타자료들\python_study\venv\04_Team8\data_08\data\Reddit\leagueoflegends\Data_leagueoflegends.csv",
    r"F:\porti\2025\스파르타자료들\python_study\venv\04_Team8\data_08\data\Reddit\LeagueOfMemes\Data_LeagueOfMemes.csv",
    r"F:\porti\2025\스파르타자료들\python_study\venv\04_Team8\data_08\data\Reddit\midlanemains\Data_midlanemains.csv",
    r"F:\porti\2025\스파르타자료들\python_study\venv\04_Team8\data_08\data\Reddit\summonerschool\Data_summonerschool.csv",
    r"F:\porti\2025\스파르타자료들\python_study\venv\04_Team8\data_08\data\Reddit\supportlol\Data_supportlol.csv",
    r"F:\porti\2025\스파르타자료들\python_study\venv\04_Team8\data_08\data\Reddit\top_mains\Data_top_mains.csv"
]

In [8]:
# 파일 불러오기
df_list = []

for path in file_paths:
    temp = pd.read_csv(path)
    print(f"{path} -> {len(temp)} rows")
    df_list.append(temp)

F:\porti\2025\스파르타자료들\python_study\venv\04_Team8\data_08\data\Reddit\ADCMains\Data_ADCMains.csv -> 15725 rows
F:\porti\2025\스파르타자료들\python_study\venv\04_Team8\data_08\data\Reddit\Jungle_Mains\Data_Jungle_Mains.csv -> 16394 rows
F:\porti\2025\스파르타자료들\python_study\venv\04_Team8\data_08\data\Reddit\leagueoflegends\Data_leagueoflegends.csv -> 44936 rows
F:\porti\2025\스파르타자료들\python_study\venv\04_Team8\data_08\data\Reddit\LeagueOfMemes\Data_LeagueOfMemes.csv -> 15209 rows
F:\porti\2025\스파르타자료들\python_study\venv\04_Team8\data_08\data\Reddit\midlanemains\Data_midlanemains.csv -> 6049 rows
F:\porti\2025\스파르타자료들\python_study\venv\04_Team8\data_08\data\Reddit\summonerschool\Data_summonerschool.csv -> 12381 rows
F:\porti\2025\스파르타자료들\python_study\venv\04_Team8\data_08\data\Reddit\supportlol\Data_supportlol.csv -> 13931 rows
F:\porti\2025\스파르타자료들\python_study\venv\04_Team8\data_08\data\Reddit\top_mains\Data_top_mains.csv -> 10044 rows

In [9]:
# 병합
df = pd.concat(df_list, ignore_index=True)

print("\n병합 완료")
print("총 행 수:", len(df))
df

병합 완료
총 행 수: 134669

,subreddit,post_id,post_title,post_created_dt,post_score,post_num_comments,comment_id,comment_author,comment_score,comment_created_dt,comment_body_raw,comment_body_clean,emoji_list,emoji_count,language
0,ADCMains,1pizrxr,ADCs in a nutshell,2025-12-10 11:00:43,8283,148,nta7jrv,lahartheviking,240,2025-12-10 13:06:48,if enemy adc is one item before me i run down mid,if enemy adc is one item before me i run down mid,[],0,en
1,ADCMains,1pizrxr,ADCs in a nutshell,2025-12-10 11:00:43,8283,148,nta0cvt,Icy-Hour-5031,232,2025-12-10 12:16:21,There are a lot of adcs that if they are behin...,there are a lot of adcs that if they are behin...,[],0,en
2,ADCMains,1pizrxr,ADCs in a nutshell,2025-12-10 11:00:43,8283,148,ntacod6,theeama,152,2025-12-10 13:38:37,Jinx ain't the champion to use here because if...,jinx aint the champion to use here because if ...,[],0,en
3,ADCMains,1pizrxr,ADCs in a nutshell,2025-12-10 11:00:43,8283,148,nta0es1,Low_Direction1774,92,2025-12-10 12:16:45,"Youre not an ADC main, are you?",youre not an adc main are you,[],0,en
4,ADCMains,1pizrxr,ADCs in a nutshell,2025-12-10 11:00:43,8283,148,ntammgw,Babushla153,37,2025-12-10 14:36:06,At that point if you die as 8/0 dairus against...,at that point if you die as 80 dairus against ...,[],0,en
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
134664,top_mains,1ogc8ju,How do I stop accidentally giving freeze every...,2025-10-26 05:09:24,8,11,nlfvy8a,The_God_of_Biscuits,0,2025-10-26 07:18:25,"If you have prio, you can crash whenever if jg...",if you have prio you can crash whenever if jg ...,[],0,en
134665,top_mains,1pc5che,"Hello fellow top mains, i have just finished w...",2025-12-02 10:44:27,8,6,nrv6swj,Desperate-Zebra-3855,15,2025-12-02 10:51:24,"As an example, Aatrox gets roughly 5 ad per le...",as an example aatrox gets roughly 5 ad per lev...,[],0,en
134666,top_mains,1pc5che,"Hello fellow top mains, i have just finished w...",2025-12-02 10:44:27,8,6,nrw4lvq,Active-Advisor5909,3,2025-12-02 14:45:32,Steraks will be slightly better. But a bonus 6...,steraks will be slightly better but a bonus 6 ...,[],0,en
134667,top_mains,1pc5che,"Hello fellow top mains, i have just finished w...",2025-12-02 10:44:27,8,6,nsg25jd,Mindless-Humor-9036,1,2025-12-05 16:21:43,I think you’re over thinking it tbh. I only go...,i think youre over thinking it tbh i only go s...,[],0,en
134668,top_mains,1r4ekpt,Volibear signed poster,2026-02-14 07:38:00,8,1,o5v2b4s,schobesa,1,2026-02-17 13:30:26,how the fuck did voli sign a poster?????????,how the fuck did voli sign a poster,[],0,en

In [10]:
# 병합 후 확인차 중복 제거 재확인
if "comment_id" in df.columns:
    before = len(df)
    df = df.drop_duplicates(subset=["comment_id"])
    after = len(df)
    print(f"중복 제거: {before - after} rows 삭제됨")

중복 제거: 0 rows 삭제됨

In [11]:
# has_emoji : 이모티콘이 있냐없냐 true/false 칼럼 추가하기

# emoji_count가 이미 있는 경우
if "emoji_count" in df.columns:
    df["has_emoji"] = df["emoji_count"] > 0

# 없는 경우 직접 계산
else:
    def has_emoji(text):
        return any(c in emoji.EMOJI_DATA for c in str(text))

    df["has_emoji"] = df["comment_body_raw"].apply(has_emoji)

print("has_emoji 컬럼 추가 완료")

has_emoji 컬럼 추가 완료

In [12]:
print("\n현재 컬럼 목록:")
print(df.columns)

print("\n결측치 총 개수:", df.isnull().sum().sum())
df

현재 컬럼 목록:
Index(['subreddit', 'post_id', 'post_title', 'post_created_dt', 'post_score',
       'post_num_comments', 'comment_id', 'comment_author', 'comment_score',
       'comment_created_dt', 'comment_body_raw', 'comment_body_clean',
       'emoji_list', 'emoji_count', 'language', 'has_emoji'],
      dtype='object')

결측치 총 개수: 469

,subreddit,post_id,post_title,post_created_dt,post_score,post_num_comments,comment_id,comment_author,comment_score,comment_created_dt,comment_body_raw,comment_body_clean,emoji_list,emoji_count,language,has_emoji
0,ADCMains,1pizrxr,ADCs in a nutshell,2025-12-10 11:00:43,8283,148,nta7jrv,lahartheviking,240,2025-12-10 13:06:48,if enemy adc is one item before me i run down mid,if enemy adc is one item before me i run down mid,[],0,en,False
1,ADCMains,1pizrxr,ADCs in a nutshell,2025-12-10 11:00:43,8283,148,nta0cvt,Icy-Hour-5031,232,2025-12-10 12:16:21,There are a lot of adcs that if they are behin...,there are a lot of adcs that if they are behin...,[],0,en,False
2,ADCMains,1pizrxr,ADCs in a nutshell,2025-12-10 11:00:43,8283,148,ntacod6,theeama,152,2025-12-10 13:38:37,Jinx ain't the champion to use here because if...,jinx aint the champion to use here because if ...,[],0,en,False
3,ADCMains,1pizrxr,ADCs in a nutshell,2025-12-10 11:00:43,8283,148,nta0es1,Low_Direction1774,92,2025-12-10 12:16:45,"Youre not an ADC main, are you?",youre not an adc main are you,[],0,en,False
4,ADCMains,1pizrxr,ADCs in a nutshell,2025-12-10 11:00:43,8283,148,ntammgw,Babushla153,37,2025-12-10 14:36:06,At that point if you die as 8/0 dairus against...,at that point if you die as 80 dairus against ...,[],0,en,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
134664,top_mains,1ogc8ju,How do I stop accidentally giving freeze every...,2025-10-26 05:09:24,8,11,nlfvy8a,The_God_of_Biscuits,0,2025-10-26 07:18:25,"If you have prio, you can crash whenever if jg...",if you have prio you can crash whenever if jg ...,[],0,en,False
134665,top_mains,1pc5che,"Hello fellow top mains, i have just finished w...",2025-12-02 10:44:27,8,6,nrv6swj,Desperate-Zebra-3855,15,2025-12-02 10:51:24,"As an example, Aatrox gets roughly 5 ad per le...",as an example aatrox gets roughly 5 ad per lev...,[],0,en,False
134666,top_mains,1pc5che,"Hello fellow top mains, i have just finished w...",2025-12-02 10:44:27,8,6,nrw4lvq,Active-Advisor5909,3,2025-12-02 14:45:32,Steraks will be slightly better. But a bonus 6...,steraks will be slightly better but a bonus 6 ...,[],0,en,False
134667,top_mains,1pc5che,"Hello fellow top mains, i have just finished w...",2025-12-02 10:44:27,8,6,nsg25jd,Mindless-Humor-9036,1,2025-12-05 16:21:43,I think you’re over thinking it tbh. I only go...,i think youre over thinking it tbh i only go s...,[],0,en,False
134668,top_mains,1r4ekpt,Volibear signed poster,2026-02-14 07:38:00,8,1,o5v2b4s,schobesa,1,2026-02-17 13:30:26,how the fuck did voli sign a poster?????????,how the fuck did voli sign a poster,[],0,en,False

In [13]:
before = len(df)

df = df[~df["comment_body_raw"].str.contains("http", na=False)]

after = len(df)

print("URL 포함 행 제거:", before - after)
print("남은 행 수:", after)

URL 포함 행 제거: 2110
남은 행 수: 132559

In [14]:
# 결측치 제거 (comment_body_clean, comment_id)
# comment_body_clean이 NaN이거나 공백인 것 제거
before = len(df)

df = df[df["comment_body_clean"].fillna("").str.strip() != ""]

after = len(df)
print("\n1. 빈 댓글 제거")
print("제거된 행 수:", before - after)
print("남은 행 수:", after)

1. 빈 댓글 제거
제거된 행 수: 81
남은 행 수: 132478

In [15]:
# comment_id가 없는 행 제거
before = len(df)

df = df[df["comment_id"].notna()]

after = len(df)
print("\n2. comment_id 결측 제거")
print("제거된 행 수:", before - after)
print("남은 행 수:", after)

2. comment_id 결측 제거
제거된 행 수: 0
남은 행 수: 132478

In [16]:
# 결측치 재확인
print("총 행 수:", len(df))
print("\n=== 결측치 개수 ===")
print(df.isnull().sum())

총 행 수: 132478

=== 결측치 개수 ===
subreddit             0
post_id               0
post_title            0
post_created_dt       0
post_score            0
post_num_comments     0
comment_id            0
comment_author        0
comment_score         0
comment_created_dt    0
comment_body_raw      1
comment_body_clean    0
emoji_list            0
emoji_count           0
language              0
has_emoji             0
dtype: int64

In [17]:
import re

def clean_text_strict(text):
    if pd.isna(text):
        return ""
    
    text = str(text)
    
    # 소문자 변환
    text = text.lower()

    # 줄바꿈만 정리
    text = text.replace("\n", " ").replace("\r", " ")
    
    # 공백 여러 개 → 하나
    text = re.sub(r"\s+", " ", text)
    
    return text.strip()

df["comment_body_clean"] = df["comment_body_raw"].apply(clean_text_strict)

print("comment_body_clean 재생성 완료")

comment_body_clean 재생성 완료

In [18]:
df

,subreddit,post_id,post_title,post_created_dt,post_score,post_num_comments,comment_id,comment_author,comment_score,comment_created_dt,comment_body_raw,comment_body_clean,emoji_list,emoji_count,language,has_emoji
0,ADCMains,1pizrxr,ADCs in a nutshell,2025-12-10 11:00:43,8283,148,nta7jrv,lahartheviking,240,2025-12-10 13:06:48,if enemy adc is one item before me i run down mid,if enemy adc is one item before me i run down mid,[],0,en,False
1,ADCMains,1pizrxr,ADCs in a nutshell,2025-12-10 11:00:43,8283,148,nta0cvt,Icy-Hour-5031,232,2025-12-10 12:16:21,There are a lot of adcs that if they are behin...,there are a lot of adcs that if they are behin...,[],0,en,False
2,ADCMains,1pizrxr,ADCs in a nutshell,2025-12-10 11:00:43,8283,148,ntacod6,theeama,152,2025-12-10 13:38:37,Jinx ain't the champion to use here because if...,jinx ain't the champion to use here because if...,[],0,en,False
3,ADCMains,1pizrxr,ADCs in a nutshell,2025-12-10 11:00:43,8283,148,nta0es1,Low_Direction1774,92,2025-12-10 12:16:45,"Youre not an ADC main, are you?","youre not an adc main, are you?",[],0,en,False
4,ADCMains,1pizrxr,ADCs in a nutshell,2025-12-10 11:00:43,8283,148,ntammgw,Babushla153,37,2025-12-10 14:36:06,At that point if you die as 8/0 dairus against...,at that point if you die as 8/0 dairus against...,[],0,en,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
134664,top_mains,1ogc8ju,How do I stop accidentally giving freeze every...,2025-10-26 05:09:24,8,11,nlfvy8a,The_God_of_Biscuits,0,2025-10-26 07:18:25,"If you have prio, you can crash whenever if jg...","if you have prio, you can crash whenever if jg...",[],0,en,False
134665,top_mains,1pc5che,"Hello fellow top mains, i have just finished w...",2025-12-02 10:44:27,8,6,nrv6swj,Desperate-Zebra-3855,15,2025-12-02 10:51:24,"As an example, Aatrox gets roughly 5 ad per le...","as an example, aatrox gets roughly 5 ad per le...",[],0,en,False
134666,top_mains,1pc5che,"Hello fellow top mains, i have just finished w...",2025-12-02 10:44:27,8,6,nrw4lvq,Active-Advisor5909,3,2025-12-02 14:45:32,Steraks will be slightly better. But a bonus 6...,steraks will be slightly better. but a bonus 6...,[],0,en,False
134667,top_mains,1pc5che,"Hello fellow top mains, i have just finished w...",2025-12-02 10:44:27,8,6,nsg25jd,Mindless-Humor-9036,1,2025-12-05 16:21:43,I think you’re over thinking it tbh. I only go...,i think you’re over thinking it tbh. i only go...,[],0,en,False
134668,top_mains,1r4ekpt,Volibear signed poster,2026-02-14 07:38:00,8,1,o5v2b4s,schobesa,1,2026-02-17 13:30:26,how the fuck did voli sign a poster?????????,how the fuck did voli sign a poster?????????,[],0,en,False

In [184]:
# 전처리 파일 최종 저장
save_path = r"F:\porti\2025\스파르타자료들\python_study\venv\04_Team8\data_08\data\Reddit\Reddit_Master_Data.csv"

df.to_csv(save_path, index=False, encoding="utf-8-sig")

print("\n저장 완료")
print("저장 경로:", save_path)
print("최종 행 수:", len(df))

저장 완료
저장 경로: F:\porti\2025\스파르타자료들\python_study\venv\04_Team8\data_08\data\Reddit\Reddit_Master_Data.csv
최종 행 수: 132478

In [19]:
# 번역 잘못될까봐 복사하여 사용
df_2 = df.copy()

In [20]:
df_2

,subreddit,post_id,post_title,post_created_dt,post_score,post_num_comments,comment_id,comment_author,comment_score,comment_created_dt,comment_body_raw,comment_body_clean,emoji_list,emoji_count,language,has_emoji
0,ADCMains,1pizrxr,ADCs in a nutshell,2025-12-10 11:00:43,8283,148,nta7jrv,lahartheviking,240,2025-12-10 13:06:48,if enemy adc is one item before me i run down mid,if enemy adc is one item before me i run down mid,[],0,en,False
1,ADCMains,1pizrxr,ADCs in a nutshell,2025-12-10 11:00:43,8283,148,nta0cvt,Icy-Hour-5031,232,2025-12-10 12:16:21,There are a lot of adcs that if they are behin...,there are a lot of adcs that if they are behin...,[],0,en,False
2,ADCMains,1pizrxr,ADCs in a nutshell,2025-12-10 11:00:43,8283,148,ntacod6,theeama,152,2025-12-10 13:38:37,Jinx ain't the champion to use here because if...,jinx ain't the champion to use here because if...,[],0,en,False
3,ADCMains,1pizrxr,ADCs in a nutshell,2025-12-10 11:00:43,8283,148,nta0es1,Low_Direction1774,92,2025-12-10 12:16:45,"Youre not an ADC main, are you?","youre not an adc main, are you?",[],0,en,False
4,ADCMains,1pizrxr,ADCs in a nutshell,2025-12-10 11:00:43,8283,148,ntammgw,Babushla153,37,2025-12-10 14:36:06,At that point if you die as 8/0 dairus against...,at that point if you die as 8/0 dairus against...,[],0,en,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
134664,top_mains,1ogc8ju,How do I stop accidentally giving freeze every...,2025-10-26 05:09:24,8,11,nlfvy8a,The_God_of_Biscuits,0,2025-10-26 07:18:25,"If you have prio, you can crash whenever if jg...","if you have prio, you can crash whenever if jg...",[],0,en,False
134665,top_mains,1pc5che,"Hello fellow top mains, i have just finished w...",2025-12-02 10:44:27,8,6,nrv6swj,Desperate-Zebra-3855,15,2025-12-02 10:51:24,"As an example, Aatrox gets roughly 5 ad per le...","as an example, aatrox gets roughly 5 ad per le...",[],0,en,False
134666,top_mains,1pc5che,"Hello fellow top mains, i have just finished w...",2025-12-02 10:44:27,8,6,nrw4lvq,Active-Advisor5909,3,2025-12-02 14:45:32,Steraks will be slightly better. But a bonus 6...,steraks will be slightly better. but a bonus 6...,[],0,en,False
134667,top_mains,1pc5che,"Hello fellow top mains, i have just finished w...",2025-12-02 10:44:27,8,6,nsg25jd,Mindless-Humor-9036,1,2025-12-05 16:21:43,I think you’re over thinking it tbh. I only go...,i think you’re over thinking it tbh. i only go...,[],0,en,False
134668,top_mains,1r4ekpt,Volibear signed poster,2026-02-14 07:38:00,8,1,o5v2b4s,schobesa,1,2026-02-17 13:30:26,how the fuck did voli sign a poster?????????,how the fuck did voli sign a poster?????????,[],0,en,False

In [21]:
df_2 = df_2[df_2["comment_body_clean"].str.contains(r"[a-zA-Z]", na=False)]
df_2

,subreddit,post_id,post_title,post_created_dt,post_score,post_num_comments,comment_id,comment_author,comment_score,comment_created_dt,comment_body_raw,comment_body_clean,emoji_list,emoji_count,language,has_emoji
0,ADCMains,1pizrxr,ADCs in a nutshell,2025-12-10 11:00:43,8283,148,nta7jrv,lahartheviking,240,2025-12-10 13:06:48,if enemy adc is one item before me i run down mid,if enemy adc is one item before me i run down mid,[],0,en,False
1,ADCMains,1pizrxr,ADCs in a nutshell,2025-12-10 11:00:43,8283,148,nta0cvt,Icy-Hour-5031,232,2025-12-10 12:16:21,There are a lot of adcs that if they are behin...,there are a lot of adcs that if they are behin...,[],0,en,False
2,ADCMains,1pizrxr,ADCs in a nutshell,2025-12-10 11:00:43,8283,148,ntacod6,theeama,152,2025-12-10 13:38:37,Jinx ain't the champion to use here because if...,jinx ain't the champion to use here because if...,[],0,en,False
3,ADCMains,1pizrxr,ADCs in a nutshell,2025-12-10 11:00:43,8283,148,nta0es1,Low_Direction1774,92,2025-12-10 12:16:45,"Youre not an ADC main, are you?","youre not an adc main, are you?",[],0,en,False
4,ADCMains,1pizrxr,ADCs in a nutshell,2025-12-10 11:00:43,8283,148,ntammgw,Babushla153,37,2025-12-10 14:36:06,At that point if you die as 8/0 dairus against...,at that point if you die as 8/0 dairus against...,[],0,en,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
134664,top_mains,1ogc8ju,How do I stop accidentally giving freeze every...,2025-10-26 05:09:24,8,11,nlfvy8a,The_God_of_Biscuits,0,2025-10-26 07:18:25,"If you have prio, you can crash whenever if jg...","if you have prio, you can crash whenever if jg...",[],0,en,False
134665,top_mains,1pc5che,"Hello fellow top mains, i have just finished w...",2025-12-02 10:44:27,8,6,nrv6swj,Desperate-Zebra-3855,15,2025-12-02 10:51:24,"As an example, Aatrox gets roughly 5 ad per le...","as an example, aatrox gets roughly 5 ad per le...",[],0,en,False
134666,top_mains,1pc5che,"Hello fellow top mains, i have just finished w...",2025-12-02 10:44:27,8,6,nrw4lvq,Active-Advisor5909,3,2025-12-02 14:45:32,Steraks will be slightly better. But a bonus 6...,steraks will be slightly better. but a bonus 6...,[],0,en,False
134667,top_mains,1pc5che,"Hello fellow top mains, i have just finished w...",2025-12-02 10:44:27,8,6,nsg25jd,Mindless-Humor-9036,1,2025-12-05 16:21:43,I think you’re over thinking it tbh. I only go...,i think you’re over thinking it tbh. i only go...,[],0,en,False
134668,top_mains,1r4ekpt,Volibear signed poster,2026-02-14 07:38:00,8,1,o5v2b4s,schobesa,1,2026-02-17 13:30:26,how the fuck did voli sign a poster?????????,how the fuck did voli sign a poster?????????,[],0,en,False

In [22]:
# 종류별 개수
lang_counts = df["language"].value_counts(dropna=False)

print("\n language 종류별 개수")
print(lang_counts)

print("\n 전체 대비 비율 (%)")
print((lang_counts / len(df) * 100).round(2))

 language 종류별 개수
language
en         117498
cy           1135
af           1071
so           1068
no            880
tl            834
it            810
fr            768
da            742
et            695
fi            657
nl            657
id            515
sv            515
pl            510
ca            456
sw            427
tr            414
ro            397
es            353
pt            308
hr            247
sl            231
sq            227
lt            215
de            185
hu            177
sk            155
lv            140
cs            103
unknown        49
vi             27
ko             12
Name: count, dtype: int64

 전체 대비 비율 (%)
language
en         88.69
cy          0.86
af          0.81
so          0.81
no          0.66
tl          0.63
it          0.61
fr          0.58
da          0.56
et          0.52
fi          0.50
nl          0.50
id          0.39
sv          0.39
pl          0.38
ca          0.34
sw          0.32
tr          0.31
ro          0.30
es          0.27
pt          0.23
hr          0.19
sl          0.17
sq          0.17
lt          0.16
de          0.14
hu          0.13
sk          0.12
lv          0.11
cs          0.08
unknown     0.04
vi          0.02
ko          0.01
Name: count, dtype: float64

In [23]:
# 영어만 필터링
df_en = df_2[df_2["language"] == "en"].copy()
print("영어 데이터:", len(df_en))

영어 데이터: 117498

In [33]:
import google.generativeai as genai
import time
import os

In [28]:
for m in genai.list_models():
    if "generateContent" in m.supported_generation_methods:
        print(m.name)

models/gemini-2.5-flash
models/gemini-2.5-pro
models/gemini-2.0-flash
models/gemini-2.0-flash-001
models/gemini-2.0-flash-exp-image-generation
models/gemini-2.0-flash-lite-001
models/gemini-2.0-flash-lite
models/gemini-2.5-flash-preview-tts
models/gemini-2.5-pro-preview-tts
models/gemma-3-1b-it
models/gemma-3-4b-it
models/gemma-3-12b-it
models/gemma-3-27b-it
models/gemma-3n-e4b-it
models/gemma-3n-e2b-it
models/gemini-flash-latest
models/gemini-flash-lite-latest
models/gemini-pro-latest
models/gemini-2.5-flash-lite
models/gemini-2.5-flash-image
models/gemini-2.5-flash-lite-preview-09-2025
models/gemini-3-pro-preview
models/gemini-3-flash-preview
models/gemini-3.1-pro-preview
models/gemini-3.1-pro-preview-customtools
models/gemini-3-pro-image-preview
models/nano-banana-pro-preview
models/gemini-robotics-er-1.5-preview
models/gemini-2.5-computer-use-preview-10-2025
models/deep-research-pro-preview-12-2025

In [30]:
model = genai.GenerativeModel("gemini-2.5-flash")

response = model.generate_content(
    "Translate this into Korean: I love playing League of Legends."
)

print(response.text)

Here are a few ways to say "I love playing League of Legends" in Korean, ranging from more formal/complete to more casual/common:

**1. Most complete and grammatically explicit:**
*   **저는 리그 오브 레전드를 하는 것을 좋아해요.**
    *   (Jeoneun Rigeu Obeu Rejeondeureul haneun geoseul joahaeyo.)
    *   *Literal translation:* "As for me, I like the act of playing League of Legends."
    *   This is polite and clear.

**2. Very common and natural (slightly more concise):**
*   **저는 리그 오브 레전드 하는 거 좋아해요.**
    *   (Jeoneun Rigeu Obeu Rejeondeu haneun geo joahaeyo.)
    *   *Explanation:* "거" is a colloquial short form of "것" (geot), making it sound a bit more casual than the first option, but still very polite and widely used.

**3. Even more concise (implying "playing"):**
*   **저는 리그 오브 레전드 좋아해요.**
    *   (Jeoneun Rigeu Obeu Rejeondeu joahaeyo.)
    *   *Explanation:* This directly translates to "I like League of Legends," but in context, it strongly implies "I like playing League of Legends." It's very common and natural among gamers.

**4. Using the common abbreviation "롤" (Rol):**
"League of Legends" is almost always shortened to "롤" (Rol) in Korean, especially by players.

*   **저는 롤 하는 거 좋아해요.**
    *   (Jeoneun Rol haneun geo joahaeyo.)
*   **저는 롤 좋아해요.**
    *   (Jeoneun Rol joahaeyo.)
    *   *Explanation:* These are the most natural and frequently used by Korean gamers.

---

**Breakdown of terms:**

*   **저 (jeo):** "I" (polite form)
*   **-는 (-neun):** Topic marker (attached to "저" to make "저는")
*   **리그 오브 레전드 (Rigeu Obeu Rejeondeu):** League of Legends (transliteration)
*   **롤 (Rol):** LoL (common abbreviation)
*   **-를/-을 (-reul/-eul):** Object particle (attached to nouns, "를" after vowel, "을" after consonant)
*   **하다 (hada):** To do / To play (verb)
*   **-는 것 (-neun geot) / -는 거 (-neun geo):** Makes a verb into a noun phrase ("the act of doing/playing")
*   **좋아해요 (joahaeyo):** "Like" / "Love" (polite present tense of 좋아하다 - to like/love)

Choose the one that best fits the context and your desired level of formality. The options with "롤" are generally the most natural in a gaming context.

In [ ]:
genai.configure(api_key="Google_AI_Studio_발급받은_키")

#genai.configure(api_key="YOUR_API_KEY")
model = genai.GenerativeModel("gemini-2.5-flash")

SAVE_PATH = "translated_progress.csv"
BATCH_SIZE = 20
SAVE_INTERVAL = 200
MIN_DELAY = 3   # 요청 간 최소 3초

# 이어서 실행 처리
if os.path.exists(SAVE_PATH):
    df_en = pd.read_csv(SAVE_PATH)
    print("기존 진행 파일 불러옴")
else:
    df_en["comment_body_ko"] = None
    print("새 번역 시작")

pending_idx = df_en[df_en["comment_body_ko"].isna()].index.tolist()
total_pending = len(pending_idx)

print(f"* 남은 번역 개수: {total_pending}")

# 배치 번역 함수 (지수 백오프 포함)
def batch_translate(text_list, max_retries=6):

    joined_text = "\n\n###\n\n".join(text_list)

    prompt = f"""
    Translate the following English texts into natural Korean.
    Keep meaning exactly the same.
    Do not summarize.
    Separate each translation with ### exactly.

    Texts:
    {joined_text}
    """

    for attempt in range(max_retries):
        try:
            response = model.generate_content(prompt)
            results = response.text.split("###")
            return [r.strip() for r in results]

        except Exception as e:
            if "429" in str(e):
                wait_time = (2 ** attempt) + random.uniform(0, 2)
                print(f"!!!429 발생!!! -> {wait_time}초 대기")
                time.sleep(wait_time)
            else:
                print("번역 실패 :", e)
                return [None] * len(text_list)

    print("!!!재시도 초과!!!")
    return [None] * len(text_list)

# 메인 루프
start_time = time.time()
processed = 0

for i in range(0, total_pending, BATCH_SIZE):

    batch_idx = pending_idx[i:i+BATCH_SIZE]
    batch_texts = df_en.loc[batch_idx, "comment_body_clean"].tolist()

    translations = batch_translate(batch_texts)

    for idx, translated in zip(batch_idx, translations):
        df_en.at[idx, "comment_body_ko"] = translated

    processed += len(batch_idx)

    elapsed = time.time() - start_time
    avg_time = elapsed / processed
    remaining = avg_time * (total_pending - processed)

    print(f"* {processed}/{total_pending} 완료")
    print(f"* 경과: {elapsed/60:.2f}분")
    print(f"* 남은 예상: {remaining/60:.2f}분")
    print("-" * 50)

    if processed % SAVE_INTERVAL == 0:
        df_en.to_csv(SAVE_PATH, index=False, encoding="utf-8-sig")
        print("===== 중간 저장 완료 =====")

    time.sleep(MIN_DELAY)  # 요청 간 강제 대기

새 번역 시작
* 남은 번역 개수: 117498
* 30/117498 완료
* 경과: 0.77분
* 남은 예상: 3021.66분
--------------------------------------------------

In [ ]:
# 최종 저장
df_en.to_csv(SAVE_PATH, index=False, encoding="utf-8-sig")
print("===== 전체 번역 완료 및 저장 완료 =====")

번역 완료 및 저장 완료